### ISSUE TITLE
Visualization: Cache data to visualization mechanism

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#118]
Provide data for external visualization tool. Heatmap good candidate: AVX, SpeedSelect, RDT, workload assignments?

**Comment by klihub** [comment]
#131 (draft PR) implements the interface for external introspection, which is supposed to be used also by visualization.

**Comment by klihub** [comment]
The missing bits from #131 are to
  - take the [first UI mockup](https://arskama.github.io/kuberGraph/index_test.html),
  - add JS-glue to produce the JSON data [expected by that UI](https://arskama.github.io/kuberGraph/datax.json) from our introspection data,
  - serve the whole shebang and [then](https://arskama.github.io/kuberGraph/d3.min.js) [some](https://arskama.github.io/kuberGraph/style.css) from the instrumentation HTTP server/service within cri-resmgr

**Comment by klihub** [comment]
Implemented by #183 .

**Comment by klihub** [comment]
PR #184 with the necessary introspection and visualization bits is ready for review.

**Comment by msivosuo** [comment]
Implemented by #184
