### ISSUE TITLE
Prototyping complex numa hierarchy

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#161]
Prototyping complex numa hierarchy

**Comment by klihub** [comment]
[This branch](https://github.com/klihub/cri-resource-manager/tree/devel/policy/memtier) is the current prototype implementation. We'll create a draft-PR once we consider it good enough as a first proto.

**Comment by klihub** [comment]
#196 is the draft PR for the 'memory tiering' policy prototype.
