### ISSUE TITLE
README improvements

### ISSUE THREAD

**Issue by sameo** [intel/cri-resource-manager#171]
I'm going through the README for the first time and I have a few suggestions for improvements:

* I would not put the CRI message dumper at the top of the README. This makes it feel like it is the main use case for the project while it's not. IMHO It's an interesting marginal usage of this project and should be mentioned from the README, but not at one of the first things people will read.

* How can I actually deploy cri-resource-manager? I was expecting a few practical, complete examples of how I could deploy, install and run cri-resource-manager. I am not sure if I have to build a webhook image, if I need to start the crm agent or not, etc. A few sequential steps on how to kick things off would be quite benefitial already, but something like a container based deployment tool or a `kubectl apply -f https://https://github.com/intel/cri-resource-manager/deploy/crm.yaml` command line would be even better

* I am also missing an overall picture of the project and how it interacts with kubernetes, kubelet and CRI-O/containerd. Overall, a high level, one illustrated paragraph architecture documentation would help.

I hope this helps, I feel this project is very valuable for the k8s ecosystem and I would love to see the README make it shine a little bit more ;-)

**Comment by marquiz** [comment]
Thanks @sameo for reading through the docs! Very valid comments and concerns. We all knew that the documentation is lacking and incoherent, but, good that somebody said that aloud :smile:

**Comment by msivosuo** [comment]
Third bullet point split out to #298. Two first ones done.

@klihub - could you link prs and move to done column, thanks!

**Comment by klihub** [comment]
#285 has been merged with limited mandatory plastic surgery on the main README. It reshuffled the content to better reflect the intended use, fixed the factual mistakes, switched minimal examples to use containerd, added dedicated section for running with docker.

However, that addressed only the most urgent problems in the README. We need more fixes/content, in particular
  - more detailed/practical deployment examples (preferably both with and without the webhook)
  - an overall architectural description (including a diagram showing how the pieces fit together)

Before those are in place, this can't/shouldn't be marked as done.

**Comment by msivosuo** [comment]
Closing, remaining opens #298 and #300 tracked in separate issues.
