### ISSUE TITLE
policy-level tri-state (on/off/auto) knob for rdt

### ISSUE THREAD

**Issue by klihub** [intel/cri-resource-manager#20]
Per-policy control whether RDT must be on, should be turned off, or is automatically taken into use if it is available. Policy MUST fail to start if RDT cannot be initialized according to this configuration (IOW, if it must be on but is not available).

**Comment by marquiz** [comment]
Implemented for static policy in #39

**Comment by marquiz** [comment]
#39 was merged. Do we want to copy this functionality to static-plus policy, too?

**Comment by msivosuo** [comment]
Closing, not relevant anymore.
