### ISSUE TITLE
Fix broken native resource requests/limits estimation heuristics.

### ISSUE THREAD

**Issue by klihub** [intel/cri-resource-manager#202]
Our native resource requests/limits estimation heuristics is now hosed. The worst offense is the memory request estimation. It is really badly broken.

The algorithm should take into account the pod's/container's apparent QoS class, which can be deducted from the pod's cgroup parent path. Fix/improve estimation to correctly handle the straightforward cases (Guaranteed, BestEffort QoS classes) and work reasonably for the rest (Burstable QoS class).

**Comment by ipuustin** [comment]
Do you mean `cache.estimateComputeResources()`? I can take a look at it.

**Comment by klihub** [comment]
I'm already halfway fixing it (and trying the whole cgroupfs handling at the same time), so let's not do overlapping work...

**Comment by ipuustin** [comment]
Ok!

**Comment by msivosuo** [comment]
@klihub - was this done already?

**Comment by klihub** [comment]
I think this was mostly fixed in commit 01eba8450ebfb8917f40b1aae2f82d46834c9615.
