### ISSUE TITLE
Add blockio and RDT class mapping to introspection data

### ISSUE THREAD

**Issue by marquiz** [intel/cri-resource-manager#232]
The controller layer contains mapping from container class to the low level class, for both RDT and blockio. This data needs to be visible in the introspection in order to be able to visualize the container classes correctly.

**Comment by klihub** [comment]
With #269 merged I'd prefer getting rid of the controller-level mappings altogether.

**Comment by klihub** [comment]
PR #292 removes support for controller-level class name transformation.
