### ISSUE TITLE
Memory tier policy

### ISSUE THREAD

**Issue by ipuustin** [intel/cri-resource-manager#234]
Implement a memory tier policy extending the topology-aware policy. The idea is to support different kinds of memory so that the containers get access to correct memory controllers. This must not cause memory overcommitment - if a container has received memory it must be guaranteed to be able to allocate that much.

**Comment by ipuustin** [comment]
Current prototype: https://github.com/intel/cri-resource-manager/pull/196

**Comment by msivosuo** [comment]
implemented by #196

**Comment by klihub** [comment]
Merged to master in #196 .
