### ISSUE TITLE
Memory Tiering: Kernel controls for limiting DRAM percentage

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#242]
Kernel controls for limiting DRAM percentage

Target: 2020-05-29

**Comment by klihub** [comment]
What is this all about ? Is this about asking Kirill's opinion if extending the *cgroup v2* implementation of the memory controller to add per-numa versions of the currently available *memory.min, memory.low, memory.high, and memory.max* control knobs would be possible ?

**Comment by kad** [comment]
This is will be delivered as kernel cgroups interface that will limit DRAM usage. CRI-RM will need to set it based on the workload metadata.

**Comment by msivosuo** [comment]
Waiting for kernel level enabling.

**Comment by msivosuo** [comment]
Requires validation on 5.5 kernel.

**Comment by klihub** [comment]
#336 Implements controls/limiting top-tier/DRAM memory usage.

**Comment by msivosuo** [comment]
Done -> closing.
