### ISSUE TITLE
Release v0.4

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#246]
# Checklist

- [x] File [a new issue](https://github.com/intel/cri-resource-manager/issues/new)
  to propose a new release. Copy this checklist into the issue description.
- [x] In the issue description, add a changelog section, describing changes
  since the last release.
- Local release preparations
  - [x] Mandatory internal release checks and preparations.
  - [x] Run `make release-tests` to run an extended set of tests prior to a release
  - [x] Run `git tag -a -m "CRI Resource Manager release $VERSION" $VERSION`.
  - [x] Create src tarballs with `make vendored-dist`
  - [x] Build RPM packages with `make cross-rpm`
  - [x] Build DEB packages with `make cross-deb`
  - [x] Upload all artefacts to Github release page.
  - [x] Build container images with `make images`
- Final verification of artefacts
  - [x] Verify the installation of binary packages
  - [x] Verify runnability of container images
- Publishing
  - [x] Push the tag with `git push $VERSION`
  - [x] Check that container images are published
    - https://hub.docker.com/r/intel/cri-resmgr-agent/tags
    - https://hub.docker.com/r/intel/cri-resmgr-webhook/tags
  - [x] Write the change log into the
  [Github release info](https://github.com/intel/cri-resource-manager/releases).
  - [x] Add a link to the tagged release in this issue.
- [x] Close this issue.

# Changelog

## Major changes
  - 'topology-aware' policy superseded by '[memtier](https://github.com/intel/cri-resource-manager/blob/v0.4.0/pkg/cri/resource-manager/policy/builtin/memtier/README.md)'
  - support for [cold start](https://github.com/intel/cri-resource-manager/blob/v0.4.0/pkg/cri/resource-manager/policy/builtin/memtier/README.md#cold-start) of containers
  - support for [dynamic demotion](https://github.com/intel/cri-resource-manager/blob/v0.4.0/pkg/cri/resource-manager/policy/builtin/memtier/README.md#dynamic-page-demotion) of memory
  - support for limiting container top tier/DRAM memory usage
  - support for externally [adjusting](https://github.com/intel/cri-resource-manager/tree/v0.4.0#container-adjustments) container resource assignments
  - multi-die aware resource allocation
  - binary distribution with packages for popular Linux distributions and images at Docker Hub

### Policies
  - 'topology-aware' policy superseded by 'memtier', which
    - is a forked and improved version of 'topology-aware'
    - has the same basic functionality
    - has a number of improvements and extra functionality:
      - multi-die topology support
      - multi-tier (DRAM/PMEM) memory support
      - top tier/DRAM memory limiting
      - container 'cold start' support: force containers initially exclusively to PMEM 
      - experimental dynamic page demotion: periodically move least-used pages from DRAM to PMEM
      - experimental support for dynamic external adjustments to container resource assignments
    - has a bunch of resource assignment/allocation fixes (which are not backported to 'topology-aware' any more)
    - will in the next release replace 'topology-aware' altogether
  - static-pools:
    - compatibility back-ports from CMK: advertise CPUs in 'shared', 'infra' pools via `CMK_CPUS_SHARED`, `CMK_CPUS_INFRA` environment variables
  - common:
    - support for new Pod annotation controls:
      - opt out from automatic topology hint generation:
        - `topologyhints.cri-resource-manager.intel.com/pod: false`
        - `topologyhints.cri-resource-manager.intel.com/container.$name: false`
      - set DRAM/top tier memory limit:
        - `toptierlimit.cri-resource-manager.intel.com/pod: $limit`
        - `toptierlimit.cri-resource-manager.intel.com/container.$name: $limit`
    - make simple container affinities always implicitly symmetric
    - limit user-defined container affinity to [-1000,1000]
    - re-trigger pod cgroupfs parent directory and QoS class discovery if necessary

### Resource controllers
  - RDT:
    - remove controller-level class name mapping
    - don't consider assignment to a default class an error if no classes are defined
    - fix crash/misplaced logging of group deletion
  - Block I/O:
    - remove controller-level class name mapping
    - don't consider assignment to a default class an error if no classes are defined
  - CRI:
    - properly send out generated/queued `UpdateContainerResources` requests

### Data collectors
  - cgroupstats:
    - use/report container IDs
    - fix hugetlb size parsing
  - avx:
    - switch to cilium/ebpf from iovisor/gobpf

### cri-resmgr
  - new command line options:
    - reset cached configuration: `--reset-config`
    - reset cached policy data: `--reset-policy`
  - always set up node agent connection, even when running with `--force-config`
  - allow switching policies during startup, unless started with `--disable-policy-switch`

### Packaging
  - install sample fallback config as fallback and not real config file
  - use `/etc/default` for defaults on debian-based distros
  - support Ubuntu 20.04, OpenSUSE 15.2

### Documentation
  - automatic generation and publishing of documentation to github pages
    - https://intel.github.io/cri-resource-manager
  - a number of documentation fixes and clarifications

### Testing
  - end-to-end test framework added

**Comment by klihub** [comment]
Here is the current draft of the changelog/release notes. Please comment/adjust as necessary:
-------------------------------------------
## Major changes
  - 'topology-aware' policy superseded by '[memtier](https://github.com/intel/cri-resource-manager/blob/master/pkg/cri/resource-manager/policy/builtin/memtier/README.md)'
  - support for [cold start](https://github.com/intel/cri-resource-manager/blob/master/pkg/cri/resource-manager/policy/builtin/memtier/README.md#cold-start) of containers
  - support for [dynamic demotion](https://github.com/intel/cri-resource-manager/blob/master/pkg/cri/resource-manager/policy/builtin/memtier/README.md#dynamic-page-demotion) of memory
  - support for limiting container top tier/DRAM memory usage
  - support for externally [adjusting](https://github.com/intel/cri-resource-manager#container-adjustments) container resource assignments
  - multi-die aware resource allocation

## Detailed changelog

### Policies
  - 'topology-aware' policy superseded by 'memtier', which
    - is a forked and improved version of 'topology-aware'
    - has the same basic functionality
    - has a number of improvements and extra functionality:
      - multi-die topology support
      - multi-tier (DRAM/PMEM) memory support
      - top tier/DRAM memory limiting
      - container 'cold start' support: force containers initially exclusively to PMEM 
      - experimental dynamic page demotion: periodically move least-used pages from DRAM to PMEM
      - experimental support for dynamic external adjustments to container resource assignments
    - has a bunch of resource assignment/allocation fixes, not backported to 'topology-aware':
      - take parent grants into account for allocable shared calculation
      - propagate exclusive allocations to parent pools/nodes
      - bug fixes for slicing off shared CPUs, prevent full exhaustion of shared CPU subsets of pools
      - fix eligible but unsatisfied isolated allocations
      - better container affinity scoring
      - fix exclusive allocation of multiple CPUs
      - fix update of affected shared CPU set after exclusive allocations
    - will in the next release replace 'topology-aware' altogether
  - static-pools:
    - compatibility back-ports from CMK:
      - advertise CPUs in 'shared', 'infra' pools via `CMK_CPUS_SHARED`, `CMK_CPUS_INFRA` environment variables
  - common:
    - new annotations:
      - opt out from automatic topology hint generation:
        - `topologyhints.cri-resource-manager.intel.com/pod: true`
        - `topologyhints.cri-resource-manager.intel.com/container.$name: true`
      - set DRAM/top tier memory limit:
        - `toptierlimit.cri-resource-manager.intel.com/pod: $limit`
        - `toptierlimit.cri-resource-manager.intel.com/container.$name: $limit`
    - make simple container affinities always implicitly symmetric
    - limit user-defined container affinity to [-1000,1000]
    - re-trigger pod cgroupfs parent directory and QoS class discovery if necessary

### Resource controllers
  - RDT:
    - remove controller-level class name mapping
    - don't consider assignment to a default class an error if no classes are defined
    - fix crash/misplaced logging of group deletion
  - Block I/O:
    - remove controller-level class name mapping
    - don't consider assignment to a default class an error if no classes are defined
  - CRI:
    - properly send out generated/queued `UpdateContainerResources` requests

### Data collectors
  - cgroupstats:
    - use/report container IDs
    - fix hugetlb size parsing
  - avx:
    - switch to cilium/ebpf from iovisor/gobpf

### cri-resmgr and cri-resmgr-agent
  - new command line options:
    - reset cached configuration: `--reset-config`
    - reset cached policy data: `--reset-policy`
  - always set up node agent connection, even when running with `--force-config`
  - allow switching policies during startup, unless started with `--disable-policy-switch`

### Packaging
  - install sample fallback config as fallback and not real config file
  - use `/etc/default` for defaults on debian-derivant distros
  - add support for Ubuntu 20.04, OpenSUSE 15.2

### Documentation
  - automatic generation and publishing of documentation to github pages
    - https://intel.github.io/cri-resource-manager
  - a number of documentation fixes and clarifications

### Testing
  - add end-to-end test framework

**Comment by marquiz** [comment]
I think the name (subject line) on the release page should be just the version, and not try to invent some heading that would capture the "leading spirit of the release" like *Improved support for Memory Tiering, Binary packages*. If you look at virtually any other project in Github the releases are simply named after the version number. I think it makes it a lot easier to grasp on quick sight. The biggest change can be the first item in the changelog/release notes

**Comment by klihub** [comment]
Release [tagged and published](https://github.com/intel/cri-resource-manager/releases/tag/v0.4.0).
