### ISSUE TITLE
AVX-512 rebalancing and rebalancing cost estimate

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#261]

**Comment by mythi** [comment]
basic functionality:
(- detect containers using avx512)
- move (during rebalance) active containers (if movable) to per package pools
- remove containers that are no longer using avx512 away from avx512 pools

**Comment by marquiz** [comment]
@klihub @mythi let's just close this one?

**Comment by mythi** [comment]
yes
