### ISSUE TITLE
Memory Tiering: safeguard from incorrect memory assignments.

### ISSUE THREAD

**Issue by kad** [intel/cri-resource-manager#282]
CRI-RM should detect situations where PMEM or HBM memory regions are marked as "movable" by the kernel (those regions will not be listed in `/sys/devices/system/node/has_normal_memory`).

If we detect that case, we should not utilize those movable regions exclusively to run workloads.
This might affect scenarios like "cold start", as well with user requests to use exclusively some regions for particular container. Might be need an option to enable failing/or fallback to mix mode?

**Comment by kad** [comment]
I think we should close this one, as @klihub  implemented it in #363 
Objections?

**Comment by msivosuo** [comment]
Makes sense to me.

**Comment by klihub** [comment]
Yes, let's close it.
