### ISSUE TITLE
High Level Arch View and Interaction w/ K8s and Friends

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#298]
I am also missing an overall picture of the project and how it interacts with kubernetes, kubelet and CRI-O/containerd. Overall, a high level, one illustrated paragraph architecture documentation would help.

split out of #171

**Comment by msivosuo** [comment]
From #171: I am also missing an overall picture of the project and how it interacts with kubernetes, kubelet and CRI-O/containerd. Overall, a high level, one illustrated paragraph architecture documentation would help.

**Comment by msivosuo** [comment]
See #420

**Comment by klihub** [comment]
#420 merged.

**Comment by marquiz** [comment]
Really good work @klihub 👍 #420 was way more than closing this issue would've required 😉
