### ISSUE TITLE
doc: more (detailed) deployment examples

### ISSUE THREAD

**Issue by klihub** [intel/cri-resource-manager#300]
Split out from #171 . Add more detailed/practical deployment examples, both with and without the webhook.

**Comment by msivosuo** [comment]
From #171: How can I actually deploy cri-resource-manager? I was expecting a few practical, complete examples of how I could deploy, install and run cri-resource-manager. I am not sure if I have to build a webhook image, if I need to start the crm agent or not, etc. A few sequential steps on how to kick things off would be quite benefitial already, but something like a container based deployment tool or a kubectl apply -f https://https://github.com/intel/cri-resource-manager/deploy/crm.yaml command line would be even better

**Comment by mmucek95** [comment]
It would be helpful to a person who runs cri-resource-manager for the first time if it contained step by step instruction. Right now I feel like these steps are missing:
 * Go installation
 * Cloning cri-rm repo
 * What stages in makefile should be done
 * Starting cri-rm service
 * Configuring cri-rm as a runtime in kubelet will work(that one is already in the README, I am living it for the context)
 * Restart kubelet

**Comment by msivosuo** [comment]
@mmucek95 - Could you check the latest documentation here: https://github.com/intel/cri-resource-manager/blob/master/docs/INSTALL.md

And let us know if the instructions now are clear and comprehensive.

**Comment by mmucek95** [comment]
LGTM

**Comment by msivosuo** [comment]
Closing based on the feedback on improvements.
