### ISSUE TITLE
Harden CPU pinning and isolation validation and documentation

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#318]
- [ ] Ensure documentation covers everything here: https://builders.intel.com/docs/networkbuilders/cpu-pin-and-isolation-in-kubernetes-app-note.pdf
- [x] Implement CPU isolation and pinning e2e validation (document (per policy) handling of isolcpus)

**Comment by askervin** [comment]
Validation implemented in #472 .

**Comment by msivosuo** [comment]
Documentation will be handled separately.
