### ISSUE TITLE
README should provide references to all the sub-documents

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#321]
README should provide references to all the sub-documents

**Comment by marquiz** [comment]
I'd vote for closing this issue. Our HTML documentation at https://intel.github.io/cri-resource-manager/docs/index.html has an auto-generated TOC/navbar. I think it does not make sense to duplicate the effort by maintaining links in the README.

**Comment by klihub** [comment]
I second that opinion.
