### ISSUE TITLE
CRI-RM not applying cpuset.mems to system

### ISSUE THREAD

**Issue by felidadae** [intel/cri-resource-manager#345]
cri-resource-manager does not apply cpuset.mems policy to the system.

cri-resource-manager logs:
lip 30 12:52:20 node38 cri-resmgr[68806]: E: [resource-control] blockio post-update hook failed: blockio: assigning container dns-autoscaler-576b576b74-wvxl5:autoscaler to class "Burstable" failed: no OCI BlockIO parameters for class "Burstable"
lip 30 12:52:20 node38 cri-resmgr[68806]: D: [resource-control] running cri post-update hook for container dns-autoscaler-576b576b74-wvxl5:autoscaler
lip 30 12:52:20 node38 cri-resmgr[68806]: D: [resource-control] running rdt post-update hook for container dns-autoscaler-576b576b74-wvxl5:autoscaler
lip 30 12:52:20 node38 cri-resmgr[68806]: E: [resource-control] rdt post-update hook failed: rdt: unknown RDT class "Burstable"
lip 30 12:52:20 node38 cri-resmgr[68806]: D: [      cache     ] removing pod 98c443d3a666fc2c24fdcbf66093c6eb380bd209f07416ba12d598a9aef0063e
lip 30 12:52:20 node38 cri-resmgr[68806]: D: [      cache     ] saving cache to file '/var/lib/cri-resmgr/cache'...
lip 30 12:52:20 node38 cri-resmgr[68806]: I: [     message    ] (intercepted) REPLY RemovePodSandbox <= {}
lip 30 12:52:25 node38 cri-resmgr[68806]: W0730 12:52:25.602785   68806 clientconn.go:1208] grpc: addrConn.createTransport failed to connect to {/var/run/cri-resmgr/cri-resmgr-agent.sock  <nil> 0 <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/run/cri-resmgr/cri-resmgr-agent.sock: connect: no such file or directory". Reconnecting...
lip 30 12:52:26 node38 cri-resmgr[68806]: I: [resource-manager] delivering policy event memtier.cold-start-done...
lip 30 12:52:26 node38 cri-resmgr[68806]: D: [     policy     ] received policy event memtier.cold-start-done with data ef86dd5c21238effa6aff6b4a8eed1ea40974f3eba8e86213096c7ef884a27bf...
lip 30 12:52:26 node38 cri-resmgr[68806]: I: [     policy     ] finishing coldstart period for pmbench-big-0:pmbench
lip 30 12:52:26 node38 cri-resmgr[68806]: I: [     policy     ] restoring memset to grant <CPU grant for pmbench-big-0:pmbench from numa node #1: exclusive: 20-24,60-63, mem: mem limit: { pmem: 100000000000, dram: 0 }>
lip 30 12:52:26 node38 cri-resmgr[68806]: D: [     policy     ] * applying grant <CPU grant for pmbench-big-0:pmbench from numa node #1: exclusive: 20-24,60-63, mem: mem limit: { pmem: 100000000000, dram: 0 }>
**lip 30 12:52:26 node38 cri-resmgr[68806]: D: [     policy     ]   => pinning to (exclusive) cpuset 20-39,60-79
lip 30 12:52:26 node38 cri-resmgr[68806]: D: [     policy     ]   => pinning to memory 1,3**
lip 30 12:52:26 node38 cri-resmgr[68806]: D: [resource-control] running blockio post-update hook for container metrics-server-667578b665-49qpt:metrics-server
lip 30 12:52:26 node38 cri-resmgr[68806]: E: [resource-control] blockio post-update hook failed: blockio: assigning container metrics-server-667578b665-49qpt:metrics-server to class "Burstable" failed: no OCI BlockIO parameters for class "Burstable"
lip 30 12:52:26 node38 cri-resmgr[68806]: D: [resource-control] running cri post-update hook for container metrics-server-667578b665-49qpt:metrics-server

Content of files, after applying policy:
sbugaj@node38 ~
  % cat /sys/fs/cgroup/cpuset/kubepods/pod30e88061-1a75-4c20-bc84-cb4a95767cea/ef86dd5c21238effa6aff6b4a8eed1ea40974f3eba8e86213096c7ef884a27bf/cpuset.cpus
20-39,60-79

sbugaj@node38 ~
  % cat /sys/fs/cgroup/cpuset/kubepods/pod30e88061-1a75-4c20-bc84-cb4a95767cea/ef86dd5c21238effa6aff6b4a8eed1ea40974f3eba8e86213096c7ef884a27bf/cpuset.mems
3

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pmbench
spec:
  template:
    metadata:
      annotations:
        cri-resource-manager.intel.com/memory-type: |
          pmbench: dram,pmem
        cri-resource-manager.intel.com/cold-start: |
          pmbench:
            duration: 60s
    spec:
      containers:
        - name: pmbench
          resources:
            requests:
              cpu: 9
              memory: 100G
            limits:
              cpu: 9
              memory: 100G

uname -r
5.5.0-1.1136.hmem1.fc31.x86_64

**Comment by ipuustin** [comment]
It seems from the logs that the policy tries to pin the memory controllers correctly, but somehow the update gets lost or is denied later. Could you test if the same behavior happens on a system with a simpler container set up such as this:

```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  annotations:
    cri-resource-manager.intel.com/memory-type: |
      nginx: dram,pmem
    cri-resource-manager.intel.com/cold-start: |
      nginx:
        duration: 10s
spec:
  containers:
  - name: nginx
    image: nginx:1.14.2
    resources:
      requests:
        cpu: 2
        memory: 100M
      limits:
        cpu: 2
        memory: 100M
```

Also, are you certain you are looking at the right container in the cgroup directory? It looks like from the spec file that you are requesting 9 cpus, but you are getting assigned 38 cpus...

**Comment by klihub** [comment]
Does you cri-resmgr binary include [092b2fbd393a85a1f944292a8803644b288993e4](https://github.com/intel/cri-resource-manager/commit/092b2fbd393a85a1f944292a8803644b288993e4) ? What is the output of `cri-resmgr --version` ?

**Comment by felidadae** [comment]
I used newer version and everything works as expected:
![image](https://user-images.githubusercontent.com/3729236/90141319-4b2a4a00-dd7b-11ea-8fdc-73a5318420a9.png)

![image](https://user-images.githubusercontent.com/3729236/90141357-58dfcf80-dd7b-11ea-94ae-d2ef2a29347d.png)
