### ISSUE TITLE
 Invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by mmucek95** [intel/cri-resource-manager#346]
Cri-resource manager fails with the following logs:
![cri-rm-fail](https://user-images.githubusercontent.com/27088196/89790386-27b89280-db22-11ea-89ea-c5b56648c55e.JPG)

uname -r
5.5.0-1.1136.hmem1.fc31.x86_64

**Comment by klihub** [comment]
Should be fixed by https://github.com/klihub/cri-resource-manager/commit/4fad59750243bd548dc1c49aad51a72cc520fa44.

**Comment by mmucek95** [comment]
Yes, it helped. Thank you for fast fix!
