### ISSUE TITLE
Create podpools policy

### ISSUE THREAD

**Issue by askervin** [intel/cri-resource-manager#402]
Create a policy that enables sharing certain sets of resources exclusively only among certain pods/containers.

Example:

policy configuration could be something like
```
exclusivePools:
  poolTypes:
    - name: Pool-A
      resources:
        cpu: 4
        memory: 16G
      capacity:
        pods: 2
      reserveHostCpus: 50 %
```

This policy can be applied to all or selected nodes only. (See [cri-resource-manager node agent](https://github.com/intel/cri-resource-manager#cri-resource-manager-node-agent).)

All nodes running with this policy configuration will:
1. Use up to half of the host CPUs (`reserveHostCpus: 50 %`) to instantiate as many `Pool-A` pools as possible.
2. Each `Pool-A` will have 4 dedicated CPUs that other containers will not be able to use.
3. Each `Pool-A` will have `capacity` for running two pods that have been annotated as `Pool-A` pods:

```
annotations:
    exclusivepools.cri-resource-manager.intel.com/pod: Pool-A
```

On a node with 32 CPUs cri-resource-manager uses 16 host CPUs for instantiating Pool-A pools. That is, there are 4 Pool-A pools on the node. As each pool has capacity for 2 pods, user can observe that there is room for 8 Pool-A pods:

```
$ kubectl describe node
...
Allocatable:
  exclusivepools.cri-resource-manager.intel.com/Pool-A/pod:  8
...
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                                                  Requests        Limits
  --------                                                  --------        ------
  exclusivepools.cri-resource-manager.intel.com/Pool-A/pod  0               0
```

User should not use container `resources.requests/limits` to allocate this kind of extended resources, as they are pod-level concept. cri-resource-manager webhook will take care of modifying created pods so that Kubernetes scheduler will deploy pods to nodes that have room for the pod in the wanted pool.

**Comment by askervin** [comment]
Implementing started. Draft version in PR #593 .

**Comment by msivosuo** [comment]
Implemented by https://github.com/intel/cri-resource-manager/pull/598
