### ISSUE TITLE
static-pools: cri-resmgr does not run as proxy before connected to cri-resmgr-agent

### ISSUE THREAD

**Issue by askervin** [intel/cri-resource-manager#457]
If `cri-resmgr` is launched and configured to run `static-pools` policy, it will not proxy CRI messages before connecting to `cri-resmgr-agent`.

This prevents, for instance, running `kubeadm init` with `static-pools` policy configured.

**Comment by marquiz** [comment]
Hmm, yes, this requirement is too strict. We need the agent for managing the node taint, node label and extended resources. I think we can start-up without the agent connection and only update the node when agent becomes available. We could add a config option to force this (i.e. require agent interface at startup), though

**Comment by klihub** [comment]
> Hmm, yes, this requirement is too strict. We need the agent for managing the node taint, node label and extended resources. I think we can start-up without the agent connection and only update the node when agent becomes available. We could add a config option to force this (i.e. require agent interface at startup), though

Sounds like a reasonable plan/approach to me.

**Comment by askervin** [comment]
This is fixed in #483. Closing.
