### ISSUE TITLE
nri study

### ISSUE THREAD

**Issue by msivosuo** [intel/cri-resource-manager#498]
**Describe the solution you'd like**

Study how the current core policy functionality of CRI-RM could be implemented using an [NRI](https://github.com/containerd/nri) plugin.

**Why this is needed**

To build a solution with broader support in the community

DoD
- [ ]  Design proposal on how to implement CRI-RM as a plugin using nri.
- [ ]  MVP Prototype

**Comment by klihub** [comment]
To get the full scope working would require a number of things.

1. Getting access to information about all running pods and containers.
This can be done by either providing a mechanism to query pod/container data (which seems difficult
with the current model and the control flow setup), or it could be achieved by providing an initial dump
of all pod/container data on startup, and then getting updates for creation/deletion.

2. Tapping into container creation/deletion/update events and an assortment of post-variants
of these. It's a bit unclear if tapping into a container stop and start events should be possible.
In principle, resources for a container could/should be freed once the container is stopped. If the
runtime is capable of (re)starting a container that has been stopped, then it would be also necessary
to tap into start events, to (re)allocate resources for containers being restarted.

3. It should be possible to update/make changes to existing running containers as a side-effect
of creating/deleting/updating (IOW, allocation/releasing/reallocting) resources. This is already
necessary for implementing very simple CPU allocation policies, like the current 'static' policy
in kubelet. There, for instance deleting/releasing a container running on a set of exclusively allocated
CPUs should add those CPUs to the cpusets of all containers that don't run on exclusive CPUs.
In the current plugin model this does not seem to be possible.

**Comment by klihub** [comment]
https://github.com/containerd/nri/issues/3

**Comment by msivosuo** [comment]
Study completed -> closing.
