### ISSUE TITLE
Rudimentary support for SST-CP

### ISSUE THREAD

**Issue by marquiz** [intel/cri-resource-manager#552]
**Describe the solution you'd like**

Rudimentary support for Speed Select Technology Core Power (SST-CP). More specifically, detect high priority CPUs by examinging the sysfs cpufreq parameters.

**Why this is needed**

Initial support for SST-CP (Ice Lake Xeon platform). Align with CMK.

**Comment by msivosuo** [comment]
Implemented by https://github.com/intel/cri-resource-manager/pull/557, closing.
