### ISSUE TITLE
rdt: add discovery mode

### ISSUE THREAD

**Issue by marquiz** [intel/cri-resource-manager#565]
**Describe the solution you'd like**
Implement a operation mode where cri-resmgr only reads the resctrl configuration from sysfs but does not try to configure it.

**Why this is needed**
Needed for cases where sysadmin wants to manage resctrl group configuration by some other means, but, wants to use cri-resmgr for assigning containers to these groups.

**Comment by msivosuo** [comment]
Implemented by #577 and #581, closing
