### ISSUE TITLE
dial unix unix:///var/run/containerd/containerd.sock: connect: no such file or directory

### ISSUE THREAD

**Issue by qingshanyinyin** [intel/cri-resource-manager#655]
**1. cri-resource-manager err**
Firstly, i set the containerd's socket file path to "/var/run/containerd/containerd.sock", and the file exists.
![image](https://user-images.githubusercontent.com/35218255/113510080-6e646c80-958b-11eb-8f0c-c95d49d59398.png)
![image](https://user-images.githubusercontent.com/35218255/113510108-99e75700-958b-11eb-8581-c352de2f8465.png)
Secondly, i set the config file (/etc/sysconfig/cri-resource-manager) of cri-resource-manger to communicate with containerd as bellow:
![image](https://user-images.githubusercontent.com/35218255/113510136-da46d500-958b-11eb-8a72-1e18bc4a8196.png)
![image](https://user-images.githubusercontent.com/35218255/113510204-4e817880-958c-11eb-8426-55a94d08a42b.png)
![image](https://user-images.githubusercontent.com/35218255/113510245-87b9e880-958c-11eb-8ef8-7a5255180c74.png)
Then, i start the cri-resource-manager, the err occurs as bellow (Error while dialing dial unix /var/run/cri-resmgr/cri-resmgr-agent.sock: connect: no such file or directory):
![image](https://user-images.githubusercontent.com/35218255/113510308-d071a180-958c-11eb-8a68-4e1022c38a04.png)
**The containerd's socket file exists, but the cri-resource-manager can not find it, Why?**
The packages is "cri-resource-manager-0.5.0-0.centos-7.x86_64.rpm" which is downloaded from [https://github.com/intel/cri-resource-manager/releases/tag/v0.5.0](https://github.com/intel/cri-resource-manager/releases/tag/v0.5.0)
 

**2. kubelet error**
when i set the kubelet args as bellow: 
KUBELET_RUNTIME="--container-runtime=remote --container-runtime-endpoint=unix:///var/run/cri-resmgr/cri-resmgr.sock"
**The error occurs  _Err :connection error: desc = "transport: Error while dialing dial unix /var/run/cri-resmgr/cri-resmgr.sock: connect: no such file or directory"_**
Is this due to the first error which cri-resource-manager service go wrong？why?

3. install and setup url
[https://intel.github.io/cri-resource-manager/stable/docs/setup.html](https://intel.github.io/cri-resource-manager/stable/docs/setup.html)

Thanks!

**Comment by klihub** [comment]
Is it possible that you are running with a containerd version where the CRI plugin defaults to disabled state ?
One easy way to check it is to make sure crictl is installed then try to run the following command to query
the runtime version over the CRI protocol:

```
crictl -r /var/run/containerd/containerd.sock version
Version:  0.1.0
RuntimeName:  containerd
RuntimeVersion:  v1.5.0-beta.3-80-g130057247.m
RuntimeApiVersion:  v1alpha2
```

If this command fails then you have the containerd CRI plugin disabled. In that case change/add this to your
containerd configuration:

```
disabled_plugins = []
```

Then restart containerd. Now the above mentioned crictl command should succeed and you should be able to
use containerd as the runtime for your K8s cluster.

**Comment by lilongfeng0902** [comment]
I have met the same question. I amazed that how the file "/var/run/cri-resmgr/cri-resmgr.sock" was produced. Can you tell me why, klihub?

**Comment by lilongfeng0902** [comment]
@qingshanyinyin Have you solved and known the reason ?

**Comment by klihub** [comment]
> I have met the same question. I amazed that how the file "/var/run/cri-resmgr/cri-resmgr.sock" was produced. Can you tell me why, klihub? @klihub

Do you have any logs ?

**Comment by lilongfeng0902** [comment]
> > I have met the same question. I amazed that how the file "/var/run/cri-resmgr/cri-resmgr.sock" was produced. Can you tell me why, klihub? @klihub
> 
> Do you have any logs ?

Just little log about the question, the key words are as above.

**Comment by klihub** [comment]
> > > I have met the same question. I amazed that how the file "/var/run/cri-resmgr/cri-resmgr.sock" was produced. Can you tell me why, klihub? @klihub
> > 
> > 
> > Do you have any logs ?
> 
> Just little log about the question, the key words are as above.

And you have verified that `crictl -r /var/run/containerd/containerd.sock version` succeeds in querying containerd's CRI plugin for the runtime and protocol versions in use ?

**Comment by lilongfeng0902** [comment]
> > > > I have met the same question. I amazed that how the file "/var/run/cri-resmgr/cri-resmgr.sock" was produced. Can you tell me why, klihub? @klihub
> > > 
> > > 
> > > Do you have any logs ?
> > 
> > 
> > Just little log about the question, the key words are as above.
> 
> And you have verified that `crictl -r /var/run/containerd/containerd.sock version` succeeds in querying containerd's CRI plugin for the runtime and protocol versions in use ?

I'm so sorry that the runtime of my kubernets cluster is docker, the version of docker is v20.10.2, the version of kubernetes is v1.20.10. The doc of setting docker is so simple, i can't understand(https://intel.github.io/cri-resource-manager/stable/docs/setup.html#using-docker-as-the-runtime). I had experienced cri-rm on the containerd runtime, not met the same question.

**Comment by lilongfeng0902** [comment]
@klihub Could you tell me that how "/var/run/cri-resmgr/cri-resmgr.sock" file was produced? or ,what should I do? Because there is no this file, setting by the doc (https://intel.github.io/cri-resource-manager/stable/docs/setup.html#using-docker-as-the-runtime), the sevice of kubelet didn't start.

**Comment by lilongfeng0902** [comment]
Maybe I didn't set the right param of docker runtime. Now I execute the command "cri-resmgr --fallback-config=/etc/cri-resmgr/fallback.cfg --runtime-socket=/var/run/dockershim.sock --image-socket=/var/run/dockershim.sock ",the error message is "transport: error while dialing: dial unix /run/dockershim.sock: connection refused".

**Comment by lilongfeng0902** [comment]
> @klihub Could you tell me that how "/var/run/cri-resmgr/cri-resmgr.sock" file was produced? or ,what should I do? Because there is no this file, setting by the doc (https://intel.github.io/cri-resource-manager/stable/docs/setup.html#using-docker-as-the-runtime), the sevice of kubelet didn't start.

Not set the right runtime param, then "CRI relay" is not created correctly.

**Comment by klihub** [comment]
`Dockershim` usage is very strongly discouraged. It is deprecated in the orchestration as well. `Dockershim` is a lossy protocol translator between CRI and the native docker protocol. Some of the controls that work with `containerd` and `cri-o` do not and will not work with `dockershim`.

**Comment by klihub** [comment]
Closing. Was result of using docker/misconfigured containerd running with a disabled CRI plugin.
