### ISSUE TITLE
Expose the cpu usage of pools to Promethues.

### ISSUE THREAD

**Issue by huangrui666** [intel/cri-resource-manager#691]
**Describe the solution you'd like**
1. Calculate the CPU usage of each pools.
2. Some details of each pods need to be exposed, such as assigned containers and pods, the size, the CPU set details and so on.

**Why this is needed**
In our project, we are using the podpools-policy and we want to use Prometheus to monitor the metrics of each pools such as the CPU usage, the assigned pods and containers and the definition of each pod and so on. And these messages can be exposed by CRI.

**Comment by huangrui666** [comment]
Hi dear maintainers,
I have create a PR to preliminarily realize this feature. Could you please help review?
https://github.com/intel/cri-resource-manager/pull/692
Any suggestions will be appreciated. Thanks very much!

**Comment by huangrui666** [comment]
New PR has been created.
https://github.com/intel/cri-resource-manager/pull/702

**Comment by klihub** [comment]
Closing, PR merged.
