### ISSUE TITLE
cri-resmgr log function issue

### ISSUE THREAD

**Issue by kunshen1** [intel/cri-resource-manager#808]
**Describe the bug**
I use the  cri-resmgr command **cri-resmgr --fallback-config /etc/cri-resmgr/fallback.cfg --log_dir /var/log --log_file cri-resmgr.log** to record log in local but I can not find the output file as the command is running. I am not sure if there is a bug in the cri-resmgr log function.

**Comment by klihub** [comment]
Yes, consider it a bug and forget about logging to files using command line options. As a workaround you can redirect both stdout and stderr of `cri-resmgr` to the desired log file.

**Comment by askervin** [comment]
@klihub, it seems these unwanted flags swim in from `k8s.io/klog`.

If we skip calling `klog.InitFlags(ctl.flags)` in `klogcontrol.go`, then they would go away. Do you have an idea do we really need them?

**Comment by klihub** [comment]
IIRC, we do need to call `InitFlags()`, so that klog gets properly set up (although I have not taken a look at its internals for a long time now). We might not want to register those flags to be directly visible and controllable through the command line... but I think as long as we use klog as the logging backend, it would make more sense to have them present and controllable (IOW fix the current breakage).

**Comment by klihub** [comment]
> **Describe the bug**
> 
> I use the cri-resmgr command **cri-resmgr --fallback-config /etc/cri-resmgr/fallback.cfg --log_dir /var/log --log_file cri-resmgr.log** to record log in local but I can not find the output file as the command is running. I am not sure if there is a bug in the cri-resmgr log function.

@kunshen1 I checked the `klog` code after a long while and the behavior you see is not a bug in `cri-resmgr`. Unfortunately it is `klog`'s normal behavior. If you set the log file name it keeps logging to `stderr`, unless you also remember to set `-logtostderr=false`.

So the right way to force logging to a file is:
```
# log only to a file
cri-resmgr -logtostderr=false -log_file=/tmp/cri-resmgr.log`
# log to a file and also to stderr
cri-resmgr -logtostderr=false -log_file=/tmp/cri-resmgr.log -alsologtostderr=true
```
