### ISSUE TITLE
Why does cri-resmgr only implement CRI apiv1alpha2 interface but not CRI apiv1?

### ISSUE THREAD

**Issue by mingliangli-lml** [intel/cri-resource-manager#870]
**Describe the solution you'd like**

**Why this is needed**

 This is my personal confusion, sorry for taking your time to reply. I would be very grateful to hear from you

**Comment by mingliangli-lml** [comment]
My fault~

**Comment by klihub** [comment]
@mingliangli-lml On which side ? Client (processes talking to `cri-resmgr`) or on the server/runtime side (`cri-resmgr` talking to the real runtime) ?

For the runtime side we have a pending PR (#781 ) that adds CRI v1 support on the runtime interface.
